import defaultMdxComponents from 'fumadocs-ui/mdx';
import type { MDXComponents } from 'mdx/types';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
  Avatar,
  AvatarFallback,
  AvatarImage,
  Badge,
  Button,
  Card,
  CardAction,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
  Checkbox,
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
  Combobox,
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
  DotsLoader,
  Input,
  Label,
  LineChart,
  BarChart,
  LoadingOverlay,
  Popover,
  PopoverAnchor,
  PopoverContent,
  PopoverTrigger,
  RadioGroup,
  RadioGroupItem,
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectLabel,
  SelectSeparator,
  SelectTrigger,
  SelectValue,
  Separator,
  Skeleton,
  Spinner,
  StatCard,
  Switch,
  Tabs,
  TabsContent,
  TabsList,
  TabsTrigger,
  Textarea,
  Toast,
  ToastAction,
  ToastDescription,
  ToastTitle,
  ToastViewport,
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from '@srui/react';
import { LivePreview } from './live-preview';
import { PresetGrid } from './preset-grid';
import { TokenPlayground } from './token-playground';
import { LoadingOverlayDemo } from './loading-overlay-demo';
import { ComboboxDemo } from './combobox-demo';
import { ToastDemo, ToastVariantsDemo } from './toast-demo';
import { CheckboxDemo } from './checkbox-demo';
import { CollapsibleDemo } from './collapsible-demo';
import { AppShellDemo } from './app-shell-demo';
import { DataTableDemo } from './data-table-demo';
import { ChartCardDemo } from './chart-card-demo';
import { FormBuilderDemo } from './form-builder-demo';
import { CommandPaletteDemo } from './command-palette-demo';
import { NotificationCenterDemo } from './notification-center-demo';
import { WizardDemo } from './wizard-demo';

export function getMDXComponents(components?: MDXComponents) {
  return {
    ...defaultMdxComponents,
    Accordion,
    AccordionContent,
    AccordionItem,
    AccordionTrigger,
    Avatar,
    AvatarFallback,
    AvatarImage,
    Badge,
    Button,
    Card,
    CardAction,
    CardContent,
    CardDescription,
    CardFooter,
    CardHeader,
    CardTitle,
    Checkbox,
    Collapsible,
    CollapsibleContent,
    CollapsibleTrigger,
    Combobox,
    Dialog,
    DialogClose,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
    DialogTrigger,
    DotsLoader,
    Input,
    Label,
    LineChart,
    BarChart,
    LoadingOverlay,
    Popover,
    PopoverAnchor,
    PopoverContent,
    PopoverTrigger,
    RadioGroup,
    RadioGroupItem,
    Select,
    SelectContent,
    SelectGroup,
    SelectItem,
    SelectLabel,
    SelectSeparator,
    SelectTrigger,
    SelectValue,
    Separator,
    Skeleton,
    Spinner,
    StatCard,
    Switch,
    Tabs,
    TabsContent,
    TabsList,
    TabsTrigger,
    Textarea,
    Toast,
    ToastAction,
    ToastDescription,
    ToastTitle,
    ToastViewport,
    Tooltip,
    TooltipContent,
    TooltipTrigger,
    LivePreview,
    PresetGrid,
    TokenPlayground,
    LoadingOverlayDemo,
    ComboboxDemo,
    ToastDemo,
    ToastVariantsDemo,
    CheckboxDemo,
    CollapsibleDemo,
    AppShellDemo,
    DataTableDemo,
    ChartCardDemo,
    FormBuilderDemo,
    CommandPaletteDemo,
    NotificationCenterDemo,
    WizardDemo,
    ...components,
  } satisfies MDXComponents;
}

export const useMDXComponents = getMDXComponents;

declare global {
  type MDXProvidedComponents = ReturnType<typeof getMDXComponents>;
}
